### ISSUE TITLE
Telefones com dígitos iguais também pode ser válido

### ISSUE THREAD

**Issue by gsantiago** [patrickpissurno/node-telefone#1]
Um exemplo é a Rádio Taxi de Curitiba, cujo um dos números de contato é (41) 3333-3333 (http://www.amocuritiba.com.br/radiotaxis/radio-taxi-cidade.html)

**Comment by patrickpissurno** [comment]
Vou ajustar. Se quiser, pode mandar PR.

**Comment by patrickpissurno** [comment]
Resolvido pela PR #4
